
Texture2D g_Depth; // the full res depth texture
uint g_mip_level;
RWTexture2D<float2> o_MinMaxDepth; // the texture we're writing min and max depths to
RWTexture2D<float4> o_MinMaxProbeUVs; // we also write what pixel corresponds to the min/max depths

uint2 g_dst_dimensions; // the dimensions of the target minmax depth texture's largest mip


[numthreads(8,8,1)]
void MinMaxDepth(uint3 did : SV_DispatchThreadID)
{
    uint3 src_dimensions;
    g_Depth.GetDimensions(0, src_dimensions.x, src_dimensions.y, src_dimensions.z);
    
    uint2 dst_dimensions;
    o_MinMaxDepth.GetDimensions(dst_dimensions.x, dst_dimensions.y); // This has a different aspect ratio for each mip unless it's a pow 2 texture
    
    // This "resizes" the texture while doing the depth minmaxing, from 1920x1080 -> 2048x1024, causes some stretching
    float2 aspect_correction = float2(src_dimensions.xy) / float2(g_dst_dimensions); // TODO: BUG: causes far right and bottom to be missed sometimes
    
    uint2 coord = did.xy; 
    uint2 probe_size = pow(2, g_mip_level);
    float2 read_coord = aspect_correction * coord * probe_size;
    float orig_depth = g_Depth.Load(int3(read_coord, 0)).r;
    float min_depth = orig_depth, max_depth = orig_depth;
    
    float2 min_uvs = read_coord / src_dimensions.xy, max_uvs = read_coord / src_dimensions.xy;
    
    for (uint y = 0; y < probe_size.y; y++)
    {
        for (uint x = 0; x < probe_size.x; x++)
        {
            float2 pos = read_coord + uint2(x, y);
            if (any(pos > src_dimensions.xy))
            {
                continue;
            }
            float d = g_Depth.Load(int3(pos, 0)).r;
            if (d < min_depth)
            {
                min_depth = d;
                min_uvs = pos / src_dimensions.xy;
            }
            else if (d > max_depth)
            {
                max_depth = d;
                max_uvs = pos / src_dimensions.xy;
            }
            //min_depth = min(min_depth, d);
            //max_depth = max(max_depth, d);
        }
    }
    o_MinMaxProbeUVs[coord] = float4(min_uvs, max_uvs);
    o_MinMaxDepth[coord] = float2(min_depth, max_depth);
}
