
Texture2D g_Depth; // the full res depth texture
uint g_mip_level;
RWTexture2D<float2> o_MinMaxDepth; // the texture we're writing to

float g_near;
float g_far;

// TODO: get worldspace depth so far is significantly further than like 0.0001 units in the standard depth buffer
float LinearizeDepth(float depth)
{

    // TODO: get actual perspective parameters
    const float near = g_near; // 0.1;
    const float far = g_far;  // 1e4;
    float ndcz = 2.0 * depth - 1.0;
    return (2.0 * near * far) / (far + near - ndcz * (far - near));
    return depth;
}

// TODO: this is WAY too slow
[numthreads(8,8,1)]
void MinMaxDepth(uint3 did : SV_DispatchThreadID)
{
    uint2 coord = did.xy; // TODO: work out coord range per mip math
    uint2 probe_size = pow(2, g_mip_level);
    uint2 read_coord = coord * probe_size;
    float orig_depth = LinearizeDepth(g_Depth.Load(int3(read_coord, 0)).r);
    float min_depth = orig_depth, max_depth = orig_depth;
    
    uint2 dimensions;
    uint unused;
    g_Depth.GetDimensions(0, dimensions.x, dimensions.y, unused);
    for (uint y = 0; y < probe_size.y; y++)
    {
        for (uint x = 0; x < probe_size.x; x++)
        {
            uint2 pos = read_coord + uint2(x, y);
            if (any(pos > dimensions))
            {
                continue;
            }
            float d = LinearizeDepth(g_Depth.Load(int3(pos, 0)).r);
            min_depth = min(min_depth, d);
            max_depth = max(max_depth, d);
        }
    }
    
    o_MinMaxDepth[coord] = float2(min_depth, max_depth);
}
