
#include "../../gpu_shared.h"


Texture2D g_Depth;
Texture2D g_GeometryNormalBuffer;
Texture2D g_VisibilityBuffer;

StructuredBuffer<uint> g_IndexBuffer;
StructuredBuffer<Instance> g_InstanceBuffer;
StructuredBuffer<Vertex> g_VertexBuffer;
StructuredBuffer<Mesh> g_MeshBuffer;
StructuredBuffer<Material> g_MaterialBuffer;
StructuredBuffer<float3x4> g_TransformBuffer;

TextureCube g_EnvironmentBuffer;
Texture2D g_TextureMaps[] : register(space99);

RaytracingAccelerationStructure g_Scene;

SamplerState g_NearestSampler;
SamplerState g_TextureSampler; // Is a linear sampler


#include "../../geometry/mesh.hlsl"
#include "../../geometry/geometry.hlsl"
#include "../../geometry/ray_tracing.hlsl"
#include "../../geometry/intersection.hlsl"
#include "../../geometry/ray_intersection.hlsl"
#include "../../math/transform.hlsl"
#include "../../math/sampling.hlsl"
#include "../../materials/material_evaluation.hlsl"

Texture2D g_MinMaxDepth;

// rc uniforms
uint g_numCascades;
uint g_cascadeId;
uint2 g_BufferDimensions;
float g_c0_length;

float GetProbeDepth(uint2 coord, uint cascade_level)
{
    //return g_Depth.Sample(g_samplerNearest, uv);
    return g_Depth.Load(int3(coord, cascade_level + 1)).r;
    //return g_Depth.SampleLevel(g_samplerNearest, uv, cascade_level + 1); // TODO: does this require Hi-Z?
}

float3 GetProbeNormal(uint2 coord)
{
    return g_GeometryNormalBuffer.Load(int3(coord, 0)).xyz;
}

float IntervalScale(uint cascade_index)
{
    if (cascade_index == 0)
        return 0.0;
    return pow(2.0, cascade_index);
    return float(1u << (1u * cascade_index));
}

// TODO: figure out how I want to structure interval lengths
float2 GetInterval(uint cascade_index, float base_length)
{
    return base_length * float2(IntervalScale(cascade_index), IntervalScale(cascade_index + 1));
}

float4 MergeInterval(float4 near, float4 far)
{
    const float3 radiance = near.rgb + (far.rgb * near.a);
    return float4(radiance, near.a * far.a);
}

float4 BilinearWeights(float2 ratio)
{
    return float4(
          (1.0 - ratio.x) * (1.0 - ratio.y)
        , ratio.x * (1.0 - ratio.y)
        , (1.0 - ratio.x) * ratio.y
        , ratio.x * ratio.y
    );
}

/*
@param dest_center the center position of the destination probe in pixels [probe_size/2, res - probe_size/2]
@param upper_probe_size the size of the bilinear probe in pixels [probe_size*2]
source: <https://m4xc.dev/articles/fundamental-rc/>
*/
void BilinearSamples(float2 dest_center, float2 upper_probe_size, out float4 weights, out uint2 base_idx)
{
    // coord of top left bilinear probe when floored
    const float2 base_coord = (dest_center / upper_probe_size) - float2(0.5, 0.5);
    const float2 ratio = frac(base_coord); // sub-bilinear probe pos
    weights = BilinearWeights(ratio);
    base_idx = uint2(floor(base_coord)); // top left bilinear probe coordinate
}

uint2 BilinearOffset(uint i)
{
    const uint2 offsets[4] = { uint2(0, 0), uint2(1, 0), uint2(0, 1), uint2(1, 1) };
    return offsets[i];
}

// TODO: account for probe depth (get from minmax depth)
float3 GetRayOrigin(float2 coord, float3 normal)
{
    float4 visibility = g_VisibilityBuffer.Load(int3(coord, 0));

    float2 barycentrics = visibility.xy;
    uint instanceID = asuint(visibility.z);
    uint primitiveID = asuint(visibility.w);

    Instance instance = g_InstanceBuffer[instanceID];
    Mesh mesh = g_MeshBuffer[instance.mesh_index];
    float3x4 transform = g_TransformBuffer[instance.transform_index];

    Triangle vertices = fetchVertices(mesh, primitiveID);
    float3 v0 = transformPoint(vertices.v0, transform);
    float3 v1 = transformPoint(vertices.v1, transform);
    float3 v2 = transformPoint(vertices.v2, transform);

    float3 world = interpolate(v0, v1, v2, barycentrics);
    float3 origin = offsetPosition(world, normal);
    return origin;
}

float4 GetRadiance(IntersectData idata, RayDesc ray)
{
    //return float4(idata.normal, 1.0);
    Material material = idata.material;
    MaterialBSDF materialBSDF = MakeMaterialBSDF(material, idata.uv);
    float3 reflectance = 0;
    if (dot(materialBSDF.emissive, materialBSDF.emissive) == 0)
    {
        // TODO: sample a light in some reasonable way (NEE?)
        // TODO: account for whether the light is occluded as well (we have no shadow maps QmQ)
        MaterialBRDF materialBRDF = MakeMaterialBRDF(material, idata.uv);
        reflectance = evaluateBRDF(materialBRDF, idata.normal, ray.Direction, normalize(float3(1, 1, 1))); 
    }
    else
    {
        reflectance = materialBSDF.emissive;
    }
    return float4(reflectance, 1);
}

/*- direction mapping: 
 *  source <https://www.shadertoy.com/view/4cjczV> -*/
#define MIRROR 0

float3 octahedral_unmap(float2 e)
{
#if MIRROR
    /* Source: <https://www.shadertoy.com/view/MdsfzN> */
    float2 m = abs(e - 0.5) + 0.5;
    float2 f = floor(m);
    float x = f.x - f.y;
    bool mirror = (x != 0.0); 
    if (mirror) e.xy = 1.0-e.xy;
#endif
    /* Provided by Alexander Sannikov */
    e = frac(e);
    e = e * 2.0 - 1.0;
    float3 v = float3(e.xy, 1.0 - abs(e.x) - abs(e.y));
    if (v.z < 0.0)
        v.xy = (1.0 - abs(v.yx)) * sign(v.xy);
    return normalize(v);
}
/* Provided by Alexander Sannikov */
float3 costheta_unmap(float2 uv)
{
    float phi = uv.x * 2.0 * PI;
    float theta = uv.y * PI;
    return float3(float2(sin(phi), cos(phi)) * sin(theta), cos(theta));
}
/*- end direction mapping -*/

#define DEBUG_DIRECTIONS 0
#define DEBUG_DISABLE_MERGING 0
#define DEBUG_DISABLE_ENV_MAP 0
#define BILATERAL_UPSAMPLING 1

Texture2D g_lastCascade;
RWTexture2D<float4> o_currentCascade;
uint2 g_CascadeTexDimensions;


[numthreads(8,8,1)]
void TraceCascades(uint3 did : SV_DispatchThreadID)
{
    // constants for this cascade
    const float cascade_index = g_cascadeId;
    const bool is_cascade_0 = cascade_index == 0;
    const float2 resolution = g_BufferDimensions; // g_CascadeTexDimensions;
    const float2 one_over_res = 1.0 / resolution;
    const float2 probe_size = pow(2, cascade_index + 1);                     // size of the probe in pixels, c0 has 2x2 pixels / probe                   // TODO: variable scaling factor for probe size per cascade
    const float2 num_probes = resolution / probe_size;                       // [res/2, res/4, res/8, ...] number of probes in x/y direction (unused?)
    const float2 interval = GetInterval(cascade_index, g_c0_length);         // the start and end distances of this cascade's interval                   // TODO: variable base length
    
    // constants for this invocation (dependent on dispatch id)
    const uint2 coord = did.xy;
    // constants for this probe
    const float2 probe_position = floor(coord / probe_size);                 // [0, num_probes] position of this probe in the grid of probes
    const float2 probe_center = probe_position * probe_size + 0.5;           // [probe_size/2, res - probe_size/2] the texel coordinate of the center of this probe (basically just recreating coord and adding .5?)
    const float2 probe_center_uv = probe_center * one_over_res;              // [0, 1] uv coordinate of this probe's center (the difference to uv = coord/res is tiiiiiny)
    // constants for this pixel
    const float2 pos_in_probe = coord % probe_size;                          // [0, probe_size] position of this pixel in the probe
    
    // get probe normal and see if it's on a surface
    float3 probe_normal = g_GeometryNormalBuffer.SampleLevel(g_TextureSampler, probe_center_uv, 0).xyz;
    const bool is_sky_pixel = dot(probe_normal, probe_normal) == 0.0;
    if(is_sky_pixel)
    {
        o_currentCascade[coord] = float4(0, 0, 0, 1);
        return; // sky pixel does not reflect
    }
    // get ray origin for this probe // TODO: different probes on min/max of depth buffer in this probe_position
    probe_normal = 2.0 * probe_normal - 1.0;
    const float3 origin = GetRayOrigin(probe_center, probe_normal);
    
    float4 t_radiance = 0;
    // TODO: Do I need to do preaveraging (4 rays per pixel)?
    {
        // get a ray direction for this pixel in the probe
        const float2 uv_in_probe = (pos_in_probe + 0.5) / probe_size;
        
        float3 direction = octahedral_unmap(uv_in_probe); // TODO: this only samples 4 points on a circle if probe_size is 4x4
        //float3 direction = costheta_unmap(uv_in_probe);
        
        // TODO: apparently I'm not supposed to do normal-aligned directions, instead do a full sphere. //
        // Does this mean I need more probe resolution? min 4x4 for octahedral map? Is there such a thing as a tetrahedral map?
        // How does this affect merging?
    
        // align direction hemisphere with normal 
        //float3 b1, b2;
        //GetOrthoVectors(probe_normal, b1, b2);
        //direction = normalize(direction.x * b1 + direction.y * b2 + direction.z * probe_normal);
    
    
        // raytrace
        float4 radiance = float4(0.0, 0.0, 0.0, 1.0);
    
#if DEBUG_DIRECTIONS
        radiance = float4(direction, 1.0);
#else
        RayDesc ray;
        ray.Direction = direction;
        ray.Origin = origin;
        ray.TMin = interval.x;
        ray.TMax = interval.y;
    
        ClosestRayQuery query = TraceRay<ClosestRayQuery>(ray);
        if (query.CommittedStatus() == COMMITTED_TRIANGLE_HIT) // ray hit something
        {
            float t = query.CommittedRayT();
            HitInfo hit = GetHitInfoRtInlineCommitted(query);
            IntersectData idata = MakeIntersectData(hit); // TODO: sample lights the correct way
            radiance.rgb = GetRadiance(idata, ray).rgb;
            //radiance.rgb = ray.Direction;
            radiance.a = 0.0; // occluded
        }
        else if (g_cascadeId >= g_numCascades) // hit nothing, sample env. map if top cascade 
        {
            radiance.rgb = g_EnvironmentBuffer.SampleLevel(g_TextureSampler, ray.Direction, 0.0).rgb * 1.0;
            radiance.a = 0;
            #if DEBUG_DISABLE_ENV_MAP
            radiance.rgb = 0;
            #endif
            //radiance.rgb = float3(1, 1, 1) * 0.03;
        }
#endif
#if !DEBUG_DISABLE_MERGING
        if (g_cascadeId <= g_numCascades)
        {
            // TODO: depth aware upsampling of upper cascade, requires per-probe depth (mips?)
            // TODO: figure out the cascade offsets
    
            // merge with upper cascade
            float2 upper_probe_size = probe_size * 2; //pow(2, cascade_index + 2);
            float4 weights;
            uint2 top_left_bilin_probe_coord;
            BilinearSamples(probe_center, upper_probe_size, weights, top_left_bilin_probe_coord);
            uint dir_index = pos_in_probe.x + probe_size.x * pos_in_probe.y;
            uint dir_count = probe_size.x * probe_size.y;
            uint base_dir_index = dir_index * 4;
        
            float4 merged = 0;
        
            // TODO: should these loops be switched? 
            // for each corresponding upper probe, average its corresponding directions
            // then sample and merge those averages? Seems to make more sense to me...
            
            // upper probe traces 4 directions corresponding to this direction in this probe, average them out
            for (uint u = 0; u < 4; u++) // for each corresponding upper direction 
            {
                uint upper_dir_index = base_dir_index + u;
                uint2 bilin_dir_coord = uint2(upper_dir_index % upper_probe_size.x, upper_dir_index / upper_probe_size.y);
                float4 bilinear_radiance = 0;
                float total_weight = 0;
                // bil(ateral|inear) sample the upper 4 probes
                for (uint i = 0; i < 4; i++) // for each upper probe
                {
                    float2 offset = BilinearOffset(i);
                    float2 bilinear_idx = top_left_bilin_probe_coord + offset;
                    float2 bilinear_texel = bilinear_idx * upper_probe_size + bilin_dir_coord;
                    float4 bilinear_interval = g_lastCascade.Load(int3(bilinear_texel, 0));
                    float weight = weights[i];
                    #if BILATERAL_UPSAMPLING
                    // TODO: min/max here? currently just doing min
                    // TODO: this simply does not work.
                    float2 bilinear_uv = bilinear_texel / resolution; // surely this can't go wrong
                    float current_depth = g_MinMaxDepth.SampleLevel(g_NearestSampler, bilinear_uv, g_cascadeId + 0).r;
                    //float current_depth = g_MinMaxDepth.SampleLevel(g_NearestSampler, bilinear_uv, 0).r;
                    float upper_depth = g_MinMaxDepth.SampleLevel(g_NearestSampler, bilinear_uv, g_cascadeId + 1).r;
                    //float2 minmax_depth = g_MinMaxDepth.SampleLevel(g_NearestSampler, bilinear_uv, g_cascadeId + 2).rg;
                    weight *= exp(-100 * abs(current_depth - upper_depth));
                    //weight *= exp(-100 * abs(minmax_depth.r - minmax_depth.g));
                    #endif
                    bilinear_radiance += MergeInterval(radiance, bilinear_interval) * weight;
                    total_weight += weight;
                }
                merged += bilinear_radiance / total_weight;
            }
        
            radiance = merged * 0.25;
        }
#endif
        t_radiance = radiance;
    } // preaveraging maybe?

    
    // return
    o_currentCascade[coord] = t_radiance;
}
