
uint g_cascadeId;
uint2 g_probesCount; 

Texture2D g_Depth;
Texture2D g_GeometryNormalBuffer;
SamplerState g_samplerNearest;

uint2 g_BufferDimensions;
RWTexture2D<float4> o_CascadeTex;


// Cascade Layout
// Rows - depth angled rays
// Columns - projection angled rays
// ._______________________________.
// |   ↗   |   ↖   |   ↙   |   ↘   |
// |_______|_______|_______|_______|
// |   ↗   |   ↖   |   ↙   |   ↘   |
// |_______|_______|_______|_______|
// |   ↗   |   ↖   |   ↙   |   ↘   |
// |_______|_______|_______|_______|
// |   ↗   |   ↖   |   ↙   |   ↘   |
// |_______|_______|_______|_______|
// |_↗_|_↑_|_↖_|_←_|_↙_|_↓_|_↘_|_↗_|
// |_↗_|_↑_|_↖_|_←_|_↙_|_↓_|_↘_|_↗_|
// |_↗_|_↑_|_↖_|_←_|_↙_|_↓_|_↘_|_↗_|
// |_↗_|_↑_|_↖_|_←_|_↙_|_↓_|_↘_|_↗_|

float GetProbeDepth(float2 uv, uint cascade_level)
{
    //return g_Depth.Sample(g_samplerNearest, uv);
    return g_Depth.SampleLevel(g_samplerNearest, uv, cascade_level + 1); // TODO: does this require Hi-Z?
}

float GetProbeNormal(uint2 coord)
{
    return g_GeometryNormalBuffer.Load(int3(coord, 0));
}

// TODO: figure out how I want to structure interval lengths
float2 GetInterval(uint cascade_index)
{
    const float factor = 0.01;
    float start = pow(2, cascade_index) * factor;
    float end = pow(2, cascade_index + 1) * factor;
    return float2(start, end);
}

RayDesc GetRay(float2 probeCenterUv, float probeDepth, float3 probeNormal, uint cascade_index)
{
    RayDesc ray_desc;
    float2 interval = GetInterval(cascade_index);
    ray_desc.TMin = interval.x;
    ray_desc.TMax = interval.y;
    // TODO: origin and direction
    return ray_desc;
}


[numthreads(8,4,1)]
void RenderCascades(uint3 did : SV_DispatchThreadID)
{
    int2 coords = int2(did.xy);
    //float2 uv = float2(coords) / float2(g_BufferDimensions);
    //o_CascadeTex[coords] = float4(uv, 0.025, 1.0);
    int2 targetCoords = coords + int2(0, 4 * g_probesCount.y);
    if (coords.x >= g_BufferDimensions.x || coords.y >= 4 * g_probesCount.y)
    {
        return; // Out of bounds
    }
    int2 probeCenterCoord = coords % g_probesCount;
    float2 probeCenterUV = float2(probeCenterCoord + 1) / float2(g_probesCount + 1);
    
    const float cascadeLevel = float(g_cascadeId);
    
    const float cascadeFactor = pow(2.0, cascadeLevel);
    const float projRays = 8.0 * cascadeFactor;
    const float depthRays = floor(4.0 * 2.0 * cascadeFactor);
    float2 angleId = float2(floor(coords.x * projRays / float(g_BufferDimensions.x)), fmod(floor(1.0 - (coords.y + 1.0) / float(g_BufferDimensions.y)) * depthRays, 4.0));
    float probeDepth = GetProbeDepth(probeCenterUV, cascadeLevel);
    float probeNormal = GetProbeNormal(probeCenterCoord);
    bool is_sky_pixel = dot(probeNormal, probeNormal) == 0.0f;
    
    if (is_sky_pixel)
    {
        o_CascadeTex[targetCoords] = float4(float3(0.0), 1.0);
        return;
    }
    
    // trace some rays
    RayDesc ray = GetRay(probeCenterUV, probeDepth, probeNormal, g_cascadeId);
    // TODO: figure out rays 
    
    o_CascadeTex[targetCoords] = float4(probeCenterUV, 0.0, 1.0);
}
