
#include "../../gpu_shared.h"

Texture2D g_GeometryNormalBuffer;
Texture2D g_VisibilityBuffer;

StructuredBuffer<uint> g_IndexBuffer;
StructuredBuffer<Instance> g_InstanceBuffer;
StructuredBuffer<Vertex> g_VertexBuffer;
StructuredBuffer<Mesh> g_MeshBuffer;
StructuredBuffer<Material> g_MaterialBuffer;
StructuredBuffer<float3x4> g_TransformBuffer;

TextureCube g_EnvironmentBuffer;
Texture2D g_TextureMaps[] : register(space99);

RaytracingAccelerationStructure g_Scene;

SamplerState g_NearestSampler;
SamplerState g_TextureSampler; // Is a linear sampler


float4x4 g_ViewProjectionInverse;


#include "../../geometry/mesh.hlsl"
#include "../../geometry/geometry.hlsl"
#include "../../geometry/ray_tracing.hlsl"
#include "../../geometry/intersection.hlsl"
#include "../../geometry/ray_intersection.hlsl"
#include "../../math/transform.hlsl"
#include "../../math/sampling.hlsl"
//#include "../../materials/material_evaluation.hlsl"
#include "../../materials/material_sampling.hlsl"
//#include "../../components/light_sampler_grid_stream/light_sampler_grid_stream.hlsl"

//#include "healpix.hlsl"

Texture2D g_VisibilityDepth;
Texture2D g_MinMaxDepth;

// rc uniforms
uint g_numCascades;
uint g_cascadeId;
uint2 g_BufferDimensions;
float g_c0_length;

// depth remapping
float g_near;
float g_far;

// camera position in world space
float3 g_Eye;

float LinearizeDepth(float depth)
{
    const float near = g_near; 
    const float far = g_far; 
    float ndcz = 2.0 * depth - 1.0;
    return (2.0 * near * far) / (far + near - ndcz * (far - near));
}

float2 LinearizeDepth(float2 depth)
{
    const float near = g_near;
    const float far = g_far;
    float2 ndcz = 2.0 * depth - 1.0;
    return (2.0 * near * far) / (far + near - ndcz * (far - near));
}

float IntervalScale(uint cascade_index)
{
    if (cascade_index == 0)
        return 0.0;
    else if (cascade_index > g_numCascades) // the top cascade should end as far away as possible if it integrates the skybox
        return FLT_MAX;
    //return pow(2.0, cascade_index);
    return float(1u << (1u * cascade_index)); // TODO: variable scale factor here, currently equiv. pow(2, idx)
}

// TODO: figure out how I want to structure interval lengths. They must be long enough to reach opposing walls, but short enough to not be noticeable at close distances
float2 GetInterval(uint cascade_index, float base_length)
{
    return base_length * float2(IntervalScale(cascade_index), IntervalScale(cascade_index + 1) + 1);
    //length(pow(2.0.xx, 0 /*cascade_index*/))); // a little bit of interval overlap, as a treat
}


float4 BilinearWeights(float2 ratio)
{
    float4 bw = float4(ratio, 1.0 - ratio);
    return bw.zxzx * bw.wwyy;
    //return float4(
    //      (1.0 - ratio.x) * (1.0 - ratio.y)
    //    , ratio.x * (1.0 - ratio.y)
    //    , (1.0 - ratio.x) * ratio.y
    //    , ratio.x * ratio.y
    //);
}

/*
@param dest_center the center position of the destination probe in pixels [probe_size/2, res - probe_size/2]
@param upper_probe_size the size of the bilinear probe in pixels [probe_size*2]
source: <https://m4xc.dev/articles/fundamental-rc/>
*/
void BilinearSamples(float2 dest_center, float2 upper_probe_size, out float4 weights, out uint2 base_idx)
{
    // coord of top left bilinear probe when floored
    const float2 base_coord = (dest_center / upper_probe_size) - float2(0.5, 0.5);
    const float2 ratio = frac(base_coord); // sub-bilinear probe pos
    weights = BilinearWeights(ratio);
    base_idx = uint2(floor(base_coord)); // top left upper probe id in upper probe grid
}

uint2 BilinearOffset(uint i)
{
    const uint2 offsets[4] = { uint2(0, 0), uint2(1, 0), uint2(0, 1), uint2(1, 1) };
    return offsets[i];
}

struct TwoPos
{
    float3 near;
    float3 far;
};

TwoPos GetRayOriginDepthAware(float2 probe_uv, float3 normal, float2 probe_depths)
{
    float2 min_max_depth = probe_depths;
    float depth = min_max_depth.r;
    
    float4x4 transform = g_ViewProjectionInverse;
    float3 scaled_normal = normal * 1;// 34.5; // wtf is this (avoid self intersections) (34.5 is minimum for sponza??)
    float3 world_min = transformPointProjection(float3(2.0f.xx * float2(probe_uv.x, 1.0f - probe_uv.y) - 1.0f.xx, depth), transform);
    float3 origin_min = offsetPosition(world_min, scaled_normal);
    depth = min_max_depth.g;
    float3 world_max = transformPointProjection(float3(2.0f.xx * float2(probe_uv.x, 1.0f - probe_uv.y) - 1.0f.xx, depth), transform); 
    float3 origin_max = offsetPosition(world_max, scaled_normal);
    TwoPos ret = {origin_min, origin_max};
    return ret;
    //return transformPointProjection(float3(2.0f * float2(probe_uv.x, 1.0f - probe_uv.y) - 1.0f, depth), transform) + normal * 1.0/32.0; // this seems safer than the admittedly cool offsetPosition(), but it's way more noticeable.
    //return transformPointProjection(float3(2.0f * float2(probe_uv.x, 1.0f - probe_uv.y) - 1.0f, depth), transform);
}

float3 GetRayOrigin(float2 probe_uv, float3 normal)
{
    float4 visibility = g_VisibilityBuffer.SampleLevel(g_NearestSampler, probe_uv, 0);

    float2 barycentrics = visibility.xy;
    uint instanceID = asuint(visibility.z);
    uint primitiveID = asuint(visibility.w);

    Instance instance = g_InstanceBuffer[instanceID];
    Mesh mesh = g_MeshBuffer[instance.mesh_index];
    float3x4 transform = g_TransformBuffer[instance.transform_index];

    Triangle vertices = fetchVertices(mesh, primitiveID);
    float3 v0 = transformPoint(vertices.v0, transform);
    float3 v1 = transformPoint(vertices.v1, transform);
    float3 v2 = transformPoint(vertices.v2, transform);

    float3 world = interpolate(v0, v1, v2, barycentrics);
    float3 origin = offsetPosition(world, normal);
    return origin;
}

float4 GetRadiance(IntersectData idata, RayDesc ray)
{
    //return float4(idata.normal, 1.0);
    Material material = idata.material;
    MaterialBSDF materialBSDF = MakeMaterialBSDF(material, idata.uv);
    float3 reflectance = 0;
    if (dot(materialBSDF.emissive, materialBSDF.emissive) == 0)
    {
        // TODO: sample a light in some reasonable way (use the gi10 hashgrid cache?)
        // TODO: account for whether the light is occluded as well (we have no shadow maps QmQ)
        // TODO: should we even look at direct lighting here? Seems stupid
        MaterialBRDF materialBRDF = MakeMaterialBRDF(material, idata.uv);
        // compute diffuse compensation term with specular dominant half-vector
        float3 specular_dominant_direction = calculateGGXSpecularDirection(idata.normal, ray.Direction, sqrt(materialBRDF.roughnessAlpha));
        float3 specular_dominant_half_vector = normalize(ray.Direction + specular_dominant_direction);
        float dotHV = saturate(dot(ray.Direction, specular_dominant_half_vector));
        float3 diffuse_compensation = diffuseCompensation(materialBRDF.F0, dotHV);

        // diffuse term
        float3 diffuse = evaluateLambert(materialBRDF.albedo) * diffuse_compensation * 0.05; // TODO: wtf am i even trying to do here
        //float3 closest_light_dir = float3(0,0,0);
        //reflectance = evaluateBRDF(materialBRDF, idata.normal, ray.Direction, normalize(closest_light_dir)); 
        reflectance = diffuse;
        reflectance = 0;
    }
    else
    {
        reflectance = materialBSDF.emissive * 1;
    }
    return float4(reflectance, 1);
}

/*- direction mapping: 
 *  source <https://www.shadertoy.com/view/4cjczV> -*/
#define MIRROR 0

float3 octahedral_unmap(float2 e)
{
#if MIRROR
    /* Source: <https://www.shadertoy.com/view/MdsfzN> */
    float2 m = abs(e - 0.5) + 0.5;
    float2 f = floor(m);
    float x = f.x - f.y;
    bool mirror = (x != 0.0); 
    if (mirror) e.xy = 1.0-e.xy;
#endif
    /* Provided by Alexander Sannikov */
    e = frac(e);
    e = e * 2.0 - 1.0;
    float3 v = float3(e.xy, 1.0 - abs(e.x) - abs(e.y));
    if (v.z < 0.0)
        v.xy = (1.0 - abs(v.yx)) * sign(v.xy);
    return normalize(v);
}
/* Provided by Alexander Sannikov */
float3 costheta_unmap(float2 uv)
{
    float phi = uv.x * 2.0 * PI;
    float theta = uv.y * PI;
    return float3(float2(sin(phi), cos(phi)) * sin(theta), cos(theta));
}
/* Decode UV *(-1.0 -> 1.0)* coordinates into a direction. */
inline float3 oct_decode(const float2 e)
{
    #define copysign(a, b) ((a) * sign(b))
    /* Equal-Area Mapping <https://pbr-book.org/4ed/Geometry_and_Transformations/Spherical_Geometry#x3-Equal-AreaMapping> */
    const float2 v = abs(e);
    const float sdist = 1.0 - (v.x + v.y);
    const float r = 1.0 - abs(sdist);
    const float phi = ((v.y - v.x) / r + 1.0) * 0.785398;
    const float r_sqr = r * r;
    const float z = copysign(1.0 - r_sqr, sdist);
    const float cos_phi = copysign(cos(phi), e.x);
    const float sin_phi = copysign(sin(phi), e.y);
    const float r_scl = r * sqrt(2.0 - r_sqr);
    return float3(cos_phi * r_scl, sin_phi * r_scl, z).xyz;
}
/*- end direction mapping -*/

#define DEBUG_DIRECTIONS 0
#define DEBUG_DISABLE_MERGING 0
#define DEBUG_DISABLE_ENV_MAP 0
#define BILATERAL_UPSAMPLING 1
#define MERGE_DIR_FIRST 0 // doesn't matter for bilinear, but bilateral has an effect here (no effect when preaveraging)
#define SPHERE_MAP_MODE 2 // 0 -> costheta, 1 -> octahedral, 2 -> octahedral (equal area)
#define PROBE_PLACEMENT 0 // 0 -> depth aware, 1 -> probe center // depth aware has issues with depth sensitive leakage

#define MINMAX_MERGE 1 // 0 -> depth aware or probe center 1 -> min+max probes

#define EPSILON 0.00001

Texture2D g_lastCascade_min;
Texture2D g_lastCascade_max;
RWTexture2D<float4> o_currentCascade_min;
RWTexture2D<float4> o_currentCascade_max;
uint2 g_CascadeTexDimensions;

// idx: [0, sample_counts.x*sample_counts.y]
// sample_counts: sqrt(rays per pixel)
// 
float2 index_to_uv_offset(uint idx, uint2 sample_counts) 
{
    float2 sample_idx = float2(idx % sample_counts.x, idx / sample_counts.x) + 0.5; // [0.5,sample_counts-0.5] eg [0.5, 3.5] for sc=4,4
    sample_idx = sample_idx - 0.5 * float2(sample_counts); // [-sample_counts/2+0.5, sample_count/2-0.5] eg [-1.5,1.5] for sc=4,4
    return sample_idx / sample_counts; //[-0.5+0.5/sample_counts, 0.5-0.5/sample_counts] eg [-3/8, 3/8] for sc=4,4
}

float4 MergeInterval(float4 near, float4 far)
{
    const float3 radiance = near.rgb + (far.rgb * near.a);
    return float4(radiance, near.a * far.a);
}

float4 TraceInterval(float2 interval, float3 origin, float3 direction, bool is_max_cascade)
{
    float4 curr_radiance = float4(0.0, 0.0, 0.0, 1.0);
    
#if DEBUG_DIRECTIONS
        curr_radiance = float4(direction, 1.0);
#else
    RayDesc ray;
    ray.Direction = direction;
    ray.Origin = origin;
    ray.TMin = interval.x;
    ray.TMax = interval.y;
        
    // TODO: BUG: there's a bunch of light leaking with long ray intervals...
    
    ClosestRayQuery query = TraceRay < ClosestRayQuery > (ray);
    if (query.CommittedStatus() != COMMITTED_NOTHING) // ray hit something
    {
        float t = query.CommittedRayT();
        HitInfo hit = GetHitInfoRtInlineCommitted(query);
        if (hit.frontFace)
        {
            IntersectData idata = MakeIntersectData(hit); // TODO: sample lights the correct way, if bounce lighting is even possible
            curr_radiance.rgb = GetRadiance(idata, ray).rgb * 1;
            //curr_radiance.rgb = ray.Direction;
            curr_radiance.a = 0.0; // occluded
        }
        else
        {
            curr_radiance.a = 0;
        }
    }
    else if (is_max_cascade) // hit nothing, sample env. map if top cascade 
    {
#if DEBUG_DISABLE_ENV_MAP
        curr_radiance.rgb = 0;
#else
        curr_radiance.rgb = g_EnvironmentBuffer.SampleLevel(g_TextureSampler, ray.Direction, 0.0).rgb * 1.0;
#endif
        curr_radiance.a = 0; // this prevents propagating cMax sky samples when lower cascades' partially occluded ray groups merge with cMax
    }
#endif
    // this is the hackest hack i've ever done
//    if (direction.z == 0)
//    {
//        curr_radiance.a = 0; // axis aligned ray will never hit axis aligned wall
//    }
    return curr_radiance;
}

float4 EdgeFunction(float4 depth_diffs)
{
    //return exp(-100 * depth_diffs);
    return (1.0 / (1e4 * depth_diffs + 1));
}

float4 MergeUpperRadiance(float4 traced_radiance, uint2 target_probe_pos, uint2 target_probe_size, uint2 pos_in_target_probe, uint target_dir_index, float target_probe_depth)
{
    const uint2 upper_probe_size = 2 * target_probe_size;
    const float2 one_over_res = 1.0 / float2(g_CascadeTexDimensions);
    #if 0 // this makes no discernable difference in quality or correctness
    uint2 nearest_upper_probe = target_probe_pos / 2; // 0,0 -> 0,0; 1,1 -> 0,0; 2,2 -> 1,1 etc. There are half as many probes in cN+1.
    uint2 pos_in_upper_probe = target_probe_pos % 2; // [0,1]
    uint2 upper_probe_tl = nearest_upper_probe - (1 - pos_in_upper_probe); 
    
    float2 ratio = frac(((target_probe_pos + 0.5) * target_probe_size) / float2(upper_probe_size) - 0.5); // Just assuming this is correct ¯\_(ツ)_/¯ its the same as BilinearSamples
    float4 weights = BilinearWeights(ratio);
    #else
    uint2 upper_probe_tl;
    float4 weights;
    BilinearSamples(((target_probe_pos + 0.5) * target_probe_size), upper_probe_size, weights, upper_probe_tl);
    #endif
    
    uint linear_dir_index = (pos_in_target_probe.x + pos_in_target_probe.y * target_probe_size.x) * 4;
    uint upper_dir_index = linear_dir_index + target_dir_index;
    //uint2 dir_offset = uint2(upper_dir_index % upper_probe_size.x, upper_dir_index / upper_probe_size.x);
    uint2 dir_offset = BilinearOffset(target_dir_index) + 2 * pos_in_target_probe;
    
#if BILATERAL_UPSAMPLING
    float2 probe_center_uv = (target_probe_pos + 0.5) * target_probe_size * one_over_res;
    float4 upper_probe_depths = 0;
    for (uint d = 0; d < 4; d++)
    {
        uint2 offset = BilinearOffset(d);
        uint2 upper_probe_id = upper_probe_tl + offset;
        
        float2 upper_probe_center_uv = (upper_probe_id + 0.5) * upper_probe_size * one_over_res; // surely this can't go wrong... (IT'S GOING WRONG)
        
        #if PROBE_PLACEMENT == 0
        float upper_depth = LinearizeDepth(g_MinMaxDepth.SampleLevel(g_NearestSampler, upper_probe_center_uv, g_cascadeId+2).r); // TODO: Does this need to be linearized??
        #elif PROBE_PLACEMENT == 1
        float upper_depth = (g_MinMaxDepth.SampleLevel(g_NearestSampler, upper_probe_center_uv, 0).r);
        #endif
        upper_probe_depths[d] = upper_depth;
    }
    float maxd = hmax(upper_probe_depths);
    float mind = hmin(upper_probe_depths);
    float diffd = maxd - mind;
    float avg = dot(upper_probe_depths, 0.25.xxxx);
    bool d_edge = (diffd / avg) > 0.075;
    
    if (d_edge)
    {
        float4 dd = abs(upper_probe_depths - LinearizeDepth(target_probe_depth));
        float4 edge_fn = EdgeFunction(dd);
        weights *= edge_fn;
    }
    weights /= hadd(weights); // normalize so total is 1
#endif
    
    float4 upper_radiance = 0.0;
    for (uint i = 0; i < 4; i++) // for each upper probe
    {
        uint2 offset = BilinearOffset(i);
        uint2 upper_probe_id = upper_probe_tl + offset;
        uint2 upper_probe_start_texel = upper_probe_id * upper_probe_size;
        uint2 sample_texel = upper_probe_start_texel + dir_offset;
        float4 upper_probe_radiance = g_lastCascade_min.Load(int3(sample_texel, 0));
        float weight = weights[i];
               
        //upper_radiance.rgb += upper_probe_radiance.rgb * weight;
        //upper_radiance.a += upper_probe_radiance.a * 0.25;
        upper_radiance += upper_probe_radiance * weight;
    }

    return MergeInterval(traced_radiance, upper_radiance);
}

float4 MinMaxMergeUpper(uint layer, float4 traced_radiance, uint2 target_probe_pos, uint2 target_probe_size, uint2 pos_in_target_probe, uint target_dir_index, float target_probe_depth)
{
    const uint2 upper_probe_size = 2 * target_probe_size;
    const float2 one_over_res = 1.0 / float2(g_CascadeTexDimensions);
    uint2 upper_probe_tl;
    float4 weights;
    BilinearSamples(((target_probe_pos + 0.5) * target_probe_size), upper_probe_size, weights, upper_probe_tl);
    
    float4 upper_probe_depths[2] = { 0.xxxx, 0.xxxx };
    for (uint i = 0; i < 4; i++)
    {
        uint2 upper_probe_id = upper_probe_tl + BilinearOffset(i);
        float2 upper_probe_center_uv = (upper_probe_id + 0.5) * upper_probe_size * one_over_res; 
        float2 upper_depths = LinearizeDepth(g_MinMaxDepth.SampleLevel(g_NearestSampler, upper_probe_center_uv, g_cascadeId+2).rg); 
        upper_probe_depths[0][i] = upper_depths.r;
        upper_probe_depths[1][i] = upper_depths.g;
    }
    
    float maxd = dot(upper_probe_depths[1], 0.25.xxxx);
    float mind = dot(upper_probe_depths[0], 0.25.xxxx);
    float diffd = maxd - mind;
    float avg = (maxd + mind) * 0.5;
    bool d_edge = (diffd / avg) > 0.075;
    
    
    
    float4 depth_diffs = max(EPSILON, abs(upper_probe_depths[1] - upper_probe_depths[0]));
    float4 depth_weights = ((LinearizeDepth(target_probe_depth) - upper_probe_depths[0]) / depth_diffs);
    depth_weights = select(depth_weights > 1.0.xxxx, 0.0.xxxx, depth_weights);
    depth_weights = select(depth_weights < 0.0.xxxx, 0.0.xxxx, depth_weights);
    //depth_weights = saturate(depth_weights);
    
    if (d_edge)
    {
        float4 dd = depth_diffs;
        float4 edge_fn = EdgeFunction(dd);
        weights *= edge_fn;
    }
    weights /= hadd(weights); // normalize so total is 1
    
    uint2 dir_offset = BilinearOffset(target_dir_index) + 2 * pos_in_target_probe;
    
    float4 upper_radiance = 0;
    
    for (uint p = 0; p < 4; p++)
    {
        uint2 upper_probe_id = upper_probe_tl + BilinearOffset(p);
        uint2 upper_probe_sample_texel = upper_probe_id * upper_probe_size + dir_offset;
        float4 upper_probe_radiance_max = g_lastCascade_min.Load(int3(upper_probe_sample_texel, 0));
        float4 upper_probe_radiance_min = g_lastCascade_max.Load(int3(upper_probe_sample_texel, 0));
        float4 max_radiance = upper_probe_radiance_max * weights[p];
        float4 min_radiance = upper_probe_radiance_min * weights[p];
        upper_radiance += lerp(min_radiance, max_radiance, depth_weights[p]);
    }
    
    return MergeInterval(traced_radiance, upper_radiance);
}

float3 index_to_direction(uint d, uint2 dir_counts, uint2 pos_in_probe, uint2 probe_size)
{
    //const uint2 dir_counts = sqrt(dir_count_per_pixel);
    float2 dir_offset = index_to_uv_offset(d, dir_counts);
    // get a ray direction for this pixel in the probe
    //float2 uv_in_probe = (pos_in_probe + 0.5 + 0.5*(BilinearOffset(d) - 0.5)) / probe_size; // this works for d in [0,3]
    float2 uv_in_probe = (pos_in_probe + 0.5 + dir_offset) / probe_size;
        
#if SPHERE_MAP_MODE == 1
    float3 direction = octahedral_unmap(uv_in_probe); 
#elif SPHERE_MAP_MODE == 2
    float3 direction = oct_decode(uv_in_probe * 2.0 - 1.0); // this is an equal-area version of the above octahedral mapping. 
#else
    float3 direction = costheta_unmap(uv_in_probe); 
#endif
    return direction;
}


[numthreads(8,8,1)]
void TraceCascadesPreAvg4(uint3 did : SV_DispatchThreadID)
{
    // constants for this cascade
    const float cascade_index = g_cascadeId;
    const bool is_cascade_0 = cascade_index == 0;
    const bool is_max_cascade = g_cascadeId == g_numCascades;
    const float2 resolution = g_CascadeTexDimensions;
    const float2 one_over_res = 1.0 / resolution;
    const uint2 probe_size = pow(2, cascade_index+1); // size of the probe in pixels, c0 has 2x2 pixels / probe                   // TODO: variable scaling factor for probe size per cascade
    const float2 num_probes = resolution / probe_size; // [res/2, res/4, res/8, ...] number of probes in x/y direction (unused?)
    const float2 interval = GetInterval(cascade_index, g_c0_length); // the start and end distances of this cascade's interval                   // TODO: variable base length
    
    // constants for this invocation (dependent on dispatch id)
    const uint2 coord = did.xy;
    if (any(coord > g_CascadeTexDimensions))
        return;
    // constants for this probe
    const uint2 probe_position = floor(coord / probe_size); // [0, num_probes] position of this probe in the grid of probes
    const float2 probe_center = (probe_position + 0.5) * probe_size; // [probe_size/2, res - probe_size/2] the texel coordinate of the center of this probe (basically just recreating coord and adding .5?)
    const float2 probe_center_uv = probe_center * one_over_res; // [0, 1] uv coordinate of this probe's center 
    // constants for this pixel
    const uint2 pos_in_probe = coord % probe_size; // [0, probe_size] position of this pixel in the probe
    
    // get probe normal and see if it's on a surface
    float3 probe_normal = g_GeometryNormalBuffer.SampleLevel(g_TextureSampler, probe_center_uv, 0).xyz;
    //float3 probe_normal = g_GeometryNormalBuffer.SampleLevel(g_TextureSampler, coord * one_over_res, 0).xyz;
    const bool is_sky_pixel = dot(probe_normal, probe_normal) == 0.0;
    if (is_sky_pixel)
    {
        o_currentCascade_min[coord] = float4(0, 0, 0, 1);
        return; // sky pixel does not reflect
    }
    // get ray origin for this probe // TODO: different probes on min/max of depth buffer in this probe_position
    probe_normal = normalize(2.0 * probe_normal - 1.0); // using this to offset the position, still getting self intersections...?
    #if !MINMAX_MERGE
    #if PROBE_PLACEMENT == 0
    const float2 probe_depths = g_MinMaxDepth.SampleLevel(g_NearestSampler, probe_center_uv, cascade_index + 1).rg;
    const TwoPos origins = GetRayOriginDepthAware(probe_center_uv, probe_normal, probe_depths);
    const float3 origin = origins.near; // TODO: BUG: this gets us a bunch of stripes...? some resolution dependency with depth and probe textures, and weird self intersections. Depends on ray length??
    #elif PROBE_PLACEMENT == 1
    const float2 probe_depths = g_MinMaxDepth.SampleLevel(g_NearestSampler, probe_center_uv, 0).rg;
    const float3 origin = GetRayOrigin(probe_center_uv, probe_normal);
    #endif
    
    
    float4 t_radiance = 0;
    // Do 4 rays this pixel
    [unroll]
    for (uint d = 0; d < 4; d++)
    {
        float3 direction = index_to_direction(d, uint2(2, 2), pos_in_probe, probe_size);
        float4 curr_radiance = TraceInterval(interval, origin, direction, is_max_cascade);
        #if !DEBUG_DISABLE_MERGING
        if (!is_max_cascade) // merge
        {
            t_radiance += MergeUpperRadiance(curr_radiance, probe_position, probe_size, pos_in_probe, d, probe_depths.r);
        }
        else
        #else
        t_radiance += g_lastCascade_min[coord];
        #endif
        {
            t_radiance += curr_radiance;
        }
    }
    o_currentCascade_min[coord] = /*t_radiance.a != 0.0 && t_radiance.a != 1.0 ? float4(1,0,1,1) :*/ t_radiance * 0.25;
    #else
    const float2 probe_depths = g_MinMaxDepth.SampleLevel(g_NearestSampler, probe_center_uv, cascade_index + 1).rg;
    const TwoPos origins = GetRayOriginDepthAware(probe_center_uv, probe_normal, probe_depths);
    const float3 probe_origins[2] = { origins.near, origins.far };
    [unroll]
    for (uint layer = 0; layer < 2; layer++)
    {
        float4 t_radiance = 0;
        [unroll]
        for (uint d = 0; d < 4; d++)
        {
            float3 direction = index_to_direction(d, uint2(2, 2), pos_in_probe, probe_size);
            float4 curr_radiance = TraceInterval(interval, probe_origins[layer], direction, is_max_cascade);
            if (!is_max_cascade) // merge
            {
                t_radiance += MinMaxMergeUpper(layer, curr_radiance, probe_position, probe_size,  pos_in_probe, d, probe_depths[layer]);
            }
            else
            {
                t_radiance += curr_radiance;
            }
        }
        RWTexture2D<float4> output_tex = layer == 0 ? o_currentCascade_min : o_currentCascade_max;
        output_tex[coord] = t_radiance * 0.25;
    }
    #endif

}



// TODO: there's a lot of temporal noise and i dont know whyyyy ( it's maybe a sync issue)
[numthreads(8,8,1)]
void TraceCascadesPreAvg16(uint3 did : SV_DispatchThreadID) 
{
    //TraceCascadesPreAvg4(did);
    //return;
    // constants for this cascade
    const float cascade_index = g_cascadeId;
    const bool is_max_cascade = g_cascadeId == g_numCascades;
    //const float2 resolution = g_BufferDimensions; 
    const float2 resolution = g_CascadeTexDimensions;
    const float2 one_over_res = 1.0 / resolution;
    const uint2 probe_size = pow(2, cascade_index); // size of the probe in pixels, c0 has 1x1 pixels / probe                   // TODO: variable scaling factor for probe size per cascade
    const float2 num_probes = resolution / probe_size; // [res/2, res/4, res/8, ...] number of probes in x/y direction (unused?)
    const float2 interval = GetInterval(cascade_index, g_c0_length); // the start and end distances of this cascade's interval                   // TODO: variable base length
    
    // constants for this invocation (dependent on dispatch id)
    const uint2 coord = did.xy;
    if (any(coord > g_CascadeTexDimensions))
        return;
    // constants for this probe
    const uint2 probe_position = floor(coord / probe_size); // [0, num_probes] position of this probe in the grid of probes
    const float2 probe_center = (probe_position + 0.5) * probe_size; // [probe_size/2, res - probe_size/2] the texel coordinate of the center of this probe (basically just recreating coord and adding .5?)
    const float2 probe_center_uv = probe_center * one_over_res; // [0, 1] uv coordinate of this probe's center 
    // constants for this pixel
    const uint2 pos_in_probe = coord % probe_size; // [0, probe_size] position of this pixel in the probe
    
    // get probe normal and see if it's on a surface
    float3 probe_normal = g_GeometryNormalBuffer.SampleLevel(g_TextureSampler, probe_center_uv, 0).xyz;
    //float3 probe_normal = g_GeometryNormalBuffer.SampleLevel(g_TextureSampler, coord * one_over_res, 0).xyz;
    const bool is_sky_pixel = dot(probe_normal, probe_normal) == 0.0;
    if (is_sky_pixel)
    {
        o_currentCascade_min[coord] = float4(0, 0, 0, 1);
        return; // sky pixel does not reflect
    }
    // get ray origin for this probe // TODO: different probes on min/max of depth buffer in this probe_position
    probe_normal = normalize(2.0 * probe_normal - 1.0); // using this to offset the position, still getting self intersections...?
    #if PROBE_PLACEMENT == 0
    const float2 probe_depths = g_MinMaxDepth.SampleLevel(g_NearestSampler, probe_center_uv, g_cascadeId+1).rg;
    const float3 origin = GetRayOriginDepthAware(probe_center_uv, probe_normal, probe_depths).near; // BUG: this gets wacky stripes everywhere, dependent on ray length...?
    #elif PROBE_PLACEMENT == 1
    const float2 probe_depths= g_MinMaxDepth.SampleLevel(g_NearestSampler, probe_center_uv, 0).rg;
    const float3 origin = GetRayOrigin(probe_center_uv, probe_normal);
    #endif
    //const uint dir_count_per_pixel = 4*4; // should always be a square number i think (does it have to be an even square? a pow2 square?)
    const uint2 dir_counts = uint2(4, 4);
    const uint dir_count_per_pixel = dir_counts.x * dir_counts.y;
    
    float4 t_radiance = 0;
    [unroll]
    for (uint d = 0; d < dir_count_per_pixel; d++) // preaverage - trace 4 rays and store average result in this pixel
    {
        float3 direction = index_to_direction(d, dir_counts, pos_in_probe, probe_size);       
        // raytrace
        float4 curr_radiance = TraceInterval(interval, origin, direction, is_max_cascade);   
        #if !DEBUG_DISABLE_MERGING
        // merge
        if (!is_max_cascade) // merging
        {
            // TODO: how the hell do I generalize this for ranges other than 0..16???????
            uint mapped_d = (d / 4 + d / 2 - 3 * (d / 4 % 2) - 4 * (d / 8)); // holy fuck what is this mapping 0..16 -> 0,0,1,1,0,0,1,1,2,2,3,3,2,2,3,3
            //uint mapped_d = (d / (dir_count_per_pixel / 4)); // map d to 0..3 to choose corresponding ray average to merge with // TODO: variable scaling
            t_radiance += MergeUpperRadiance(curr_radiance, probe_position, probe_size, pos_in_probe, mapped_d, probe_depths.r);
        } // merging
        else // max cascade only needs curr_radiance
        #else
        t_radiance += g_lastCascade_min[coord];
        #endif
        {
            t_radiance += curr_radiance;
        }
    } // preaveraging 

    // return
    o_currentCascade_min[coord] = t_radiance / dir_count_per_pixel;
    //o_currentCascade_min[coord] = t_radiance / (t_radiance + 10.0);
    
}

void DebugInfo(uint3 did)
{
    // constants for this cascade
    const float cascade_index = g_cascadeId;
    const bool is_cascade_0 = cascade_index == 0;
    const bool is_max_cascade = g_cascadeId == g_numCascades;
    const float2 resolution = g_CascadeTexDimensions;
    const float2 one_over_res = 1.0 / resolution;
    const uint2 probe_size = pow(2, cascade_index + 1); // size of the probe in pixels, c0 has 2x2 pixels / probe                   // TODO: variable scaling factor for probe size per cascade
    const float2 num_probes = resolution / probe_size; // [res/2, res/4, res/8, ...] number of probes in x/y direction (unused?)
    const float2 interval = GetInterval(cascade_index, g_c0_length); // the start and end distances of this cascade's interval                   // TODO: variable base length
    
    // constants for this invocation (dependent on dispatch id)
    const uint2 coord = did.xy;
    if (any(coord > g_CascadeTexDimensions))
        return;
    // constants for this probe
    const uint2 probe_position = floor(coord / probe_size); // [0, num_probes] position of this probe in the grid of probes
    const float2 probe_center = (probe_position + 0.5) * probe_size; // [probe_size/2, res - probe_size/2] the texel coordinate of the center of this probe (basically just recreating coord and adding .5?)
    const float2 probe_center_uv = probe_center * one_over_res; // [0, 1] uv coordinate of this probe's center 
    // constants for this pixel
    const uint2 pos_in_probe = coord % probe_size; // [0, probe_size] position of this pixel in the probe
    
    // get probe normal and see if it's on a surface

    float3 probe_normal = g_GeometryNormalBuffer.SampleLevel(g_TextureSampler, probe_center_uv, 0).xyz;
    const bool is_sky_pixel = dot(probe_normal, probe_normal) == 0.0;
    if (is_sky_pixel)
    {
        o_currentCascade_min[coord] = float4(0, 0, 0, 1);
        return; // sky pixel does not reflect
    }
    // get ray origin for this probe // TODO: different probes on min/max of depth buffer in this probe_position
    probe_normal = normalize(2.0 * probe_normal - 1.0); // using this to offset the position, still getting self intersections...?
    const float2 probe_depths = g_MinMaxDepth.SampleLevel(g_NearestSampler, probe_center_uv, g_cascadeId + 1).rg;
    float3 origin = GetRayOriginDepthAware(probe_center_uv, probe_normal, probe_depths).near; // TODO: BUG: this gets us a bunch of stripes...? some resolution dependency with depth and probe textures, and weird self intersections. Depends on ray length??

    const float3 origin2 = GetRayOrigin(probe_center_uv, probe_normal);
    
    float4 t_radiance = 0;
    uint d = 0;
    float3 direction = normalize(float3(0, 0, 1)); //index_to_direction(d, uint2(2, 2), pos_in_probe, probe_size);
    //direction = normalize(origin - g_Eye);
    
    float3 ray_start = origin + direction * interval.x;
    float3 ray_start2 = origin2 + direction * interval.x;
    origin = ray_start;
    
    float wallz = 0; //-1.04;
    float3 f = 0;
    if (false || abs(origin.z - wallz) < 0.05)
    {
        f = (wallz - origin.z);
        f = select(f > 0, float3(0, 1, 0), float3(1,0,0));
    }
    else
    {
        f = origin;
    }
    o_currentCascade_min[coord] = float4(f, 1);
}

[numthreads(8,8,1)]
void TraceCascades(uint3 did : SV_DispatchThreadID)
{
    DebugInfo(did);
    return;
    // constants for this cascade
    const float cascade_index = g_cascadeId;
    const bool is_cascade_0 = cascade_index == 0;
    const bool is_max_cascade = g_cascadeId == g_numCascades;
    //const float2 resolution = g_BufferDimensions; 
    const float2 resolution = g_CascadeTexDimensions;
    const float2 one_over_res = 1.0 / resolution;
    const float2 probe_size = pow(2, cascade_index + 2);                     // size of the probe in pixels, c0 has 4x4 pixels / probe                   // TODO: variable scaling factor for probe size per cascade
    const float2 num_probes = resolution / probe_size;                       // [res/2, res/4, res/8, ...] number of probes in x/y direction (unused?)
    const float2 interval = GetInterval(cascade_index, g_c0_length);         // the start and end distances of this cascade's interval                   // TODO: variable base length
    
    // constants for this invocation (dependent on dispatch id)
    const uint2 coord = did.xy;
    // constants for this probe
    const float2 probe_position = floor(coord / probe_size);                 // [0, num_probes] position of this probe in the grid of probes
    const float2 probe_center = (probe_position + 0.5) * probe_size; // [probe_size/2, res - probe_size/2] the texel coordinate of the center of this probe (basically just recreating coord and adding .5?)
    const float2 probe_center_uv = probe_center * one_over_res;              // [0, 1] uv coordinate of this probe's center (the difference to uv = coord/res is tiiiiiny)
    // constants for this pixel
    const float2 pos_in_probe = coord % probe_size;                          // [0, probe_size] position of this pixel in the probe
    
    // get probe normal and see if it's on a surface
    float3 probe_normal = g_GeometryNormalBuffer.SampleLevel(g_TextureSampler, probe_center_uv, 0).xyz;
    const bool is_sky_pixel = dot(probe_normal, probe_normal) == 0.0;
    if(is_sky_pixel)
    {
        o_currentCascade_min[coord] = float4(0, 0, 0, 1);
        return; // sky pixel does not reflect
    }
    // get ray origin for this probe // TODO: different probes on min/max of depth buffer in this probe_position
    probe_normal = 2.0 * probe_normal - 1.0; // using this to offset the position, still getting self intersections...? Maybe they don't matter since i'm gonna average these out next pass?
    //const float3 origin = GetRayOriginDepthAware(probe_center_uv, probe_normal, g_cascadeId + 1); 
    const float3 origin = GetRayOrigin(probe_center_uv, probe_normal);
    
    float4 t_radiance = 0;

    // get a ray direction for this pixel in the probe
    const float2 uv_in_probe = (pos_in_probe + 0.5) / probe_size;
    #if SPHERE_MAP_MODE == 1
    float3 direction = octahedral_unmap(uv_in_probe); // TODO: this only samples 4 points on a circle if probe_size is 2x2
    #elif SPHERE_MAP_MODE == 0
    float3 direction = costheta_unmap(uv_in_probe);
    #elif SPHERE_MAP_MODE == 2
    float3 direction = oct_decode(uv_in_probe * 2.0 - 1.0);
    #endif
    
    //o_currentCascade_min[coord] = float4(direction, 1.0);
    //return;
    
    // raytrace
    float4 radiance = TraceInterval(interval, origin, direction, is_max_cascade);
#if !DEBUG_DISABLE_MERGING
    if (!is_max_cascade)
    {
        // TODO: depth aware upsampling of upper cascade, requires per-probe depth (mips?)
        // TODO: figure out the cascade offsets
    
        // merge with upper cascade
        float2 upper_probe_size = probe_size * 2; //pow(2, cascade_index + 2);
        float4 weights;
        uint2 top_left_bilin_probe_coord;
        BilinearSamples(probe_center, upper_probe_size, weights, top_left_bilin_probe_coord);
        uint dir_index = pos_in_probe.x + probe_size.x * pos_in_probe.y;
        uint dir_count = probe_size.x * probe_size.y;
        uint base_dir_index = dir_index * 4;
        
        float4 merged = 0;
        float total_weight = 0;
        
        // TODO: should these loops be switched? 
        // for each corresponding upper probe, average its corresponding directions
        // then sample and merge those averages? Seems to make more sense to me...
            
        #if MERGE_DIR_FIRST
        // upper probe traces 4 directions corresponding to this direction in this probe, average them out
        for (uint u = 0; u < 4; u++) // for each corresponding upper direction 
        {
            uint upper_dir_index = base_dir_index + u;
            uint2 bilin_dir_coord = uint2(upper_dir_index % upper_probe_size.x, upper_dir_index / upper_probe_size.y);
            float4 bilinear_radiance = 0;
            float total_weight = 0;
            // bil(ateral|inear) sample the upper 4 probes
            for (uint i = 0; i < 4; i++) // for each upper probe
            {
                float2 offset = BilinearOffset(i);
                float2 bilinear_idx = top_left_bilin_probe_coord + offset;
                float2 bilinear_texel = bilinear_idx * upper_probe_size + bilin_dir_coord;
                float4 bilinear_interval = g_lastCascade_min.Load(int3(bilinear_texel, 0));
                float weight = weights[i];
#if BILATERAL_UPSAMPLING
                // TODO: min/max here? currently just doing min
                // TODO: this simply does not work.
                float2 bilinear_uv = bilinear_texel * one_over_res; // surely this can't go wrong
                float current_depth = LinearizeDepth(g_MinMaxDepth.SampleLevel(g_NearestSampler, bilinear_uv, g_cascadeId + 0).r);
                //float current_depth = LinearizeDepth(g_MinMaxDepth.SampleLevel(g_NearestSampler, bilinear_uv, 0).r);
                float upper_depth = LinearizeDepth(g_MinMaxDepth.SampleLevel(g_NearestSampler, bilinear_uv, g_cascadeId + 1).r);
                weight *= max(exp(-100 * abs(current_depth - upper_depth)), EPSILON);
                //float2 minmax_depth = g_MinMaxDepth.SampleLevel(g_NearestSampler, bilinear_uv, g_cascadeId + 2).rg;
                //weight *= exp(-100 * abs(LinearizeDepth(minmax_depth.r) - LinearizeDepth(minmax_depth.g)));
#endif
                bilinear_radiance += MergeInterval(radiance, bilinear_interval) * weight;
                total_weight += weight;
            }
            merged += bilinear_radiance / total_weight;
        }
        radiance = merged * 0.25;
        #else
        // for each upper probe
        for (uint i = 0; i < 4; i++)
        {
            float2 offset = BilinearOffset(i);
            float2 bilinear_idx = top_left_bilin_probe_coord + offset;
            float4 bilinear_interval = 0;
            // for each direction in uppper probe
            for (uint d = 0; d < 4; d++)
            {
                uint upper_dir_index = base_dir_index + d;
                uint2 bilin_dir_coord = uint2(upper_dir_index % upper_probe_size.x, upper_dir_index / upper_probe_size.y);
                float2 bilinear_texel = bilinear_idx * upper_probe_size + bilin_dir_coord;
                float4 samp = g_lastCascade_min.Load(int3(bilinear_texel, 0));
                bilinear_interval += samp;
            }
            bilinear_interval *= 0.25; // average out the corresponding directions
                
            float weight = weights[i];
            #if BILATERAL_UPSAMPLING
            float2 bilinear_uv = (bilinear_idx) * upper_probe_size * one_over_res; // surely this can't go wrong
            //float current_depth = LinearizeDepth(g_MinMaxDepth.SampleLevel(g_NearestSampler, probe_center_uv, g_cascadeId + 0).r);
            float current_depth = (g_MinMaxDepth.SampleLevel(g_NearestSampler, probe_center_uv, g_cascadeId + 0).r);
            
            //float upper_depth = LinearizeDepth(g_MinMaxDepth.SampleLevel(g_NearestSampler, bilinear_uv, g_cascadeId + 1).r);
            float upper_depth = (g_MinMaxDepth.SampleLevel(g_NearestSampler, bilinear_uv, g_cascadeId + 1).r);
            
            weight *= max(exp(-100 * abs(current_depth - upper_depth)), EPSILON);
            #endif
            merged += MergeInterval(radiance, bilinear_interval) * weight;
            total_weight += weight;
        }
        //if (total_weight == 0.0 || isnan(total_weight) || isinf(total_weight))
        //    radiance.rgb = float3(1, 0, 1);
        //else 
            radiance = merged / total_weight;
        #endif
    }
#endif
    t_radiance = radiance;

    
    // return
    o_currentCascade_min[coord] = t_radiance;
}

//    0     1     2     3     4     5     6     7     8     9     10    11    12    13    14    15
//   +-----------------------------------------------------------------------------------------------+
//  0|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|
//   |__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|
//   +-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
//  1|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|
//   |__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|
//   +-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
//  2|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|
//   |__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|
//   +-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
//  3|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|
//   |__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|
//   +-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
//  4|__.__|__.__|__.__|__.__|__.__|__.__|__.__|\\.//|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|
//   |__.__|__.__|__.__|__.__|__.__|__.__|__.__|//.\\|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|
//   +-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
//  5|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|
//   |__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|
//   +-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
//  6|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|
//   |__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|
//   +-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
//  7|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|
//   |__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|
//   +-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
//  8|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|
//   |__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|__.__|
//   +-----------------------------------------------------------------------------------------------+

Texture2D g_finalCascade_min;
Texture2D g_finalCascade_max;
RWTexture2D<float4> o_finalCascadeUpscaled_min;
RWTexture2D<float4> o_finalCascadeUpscaled_max;

[numthreads(8,8,1)]
void AverageFinalCascade(uint3 did : SV_DispatchThreadID) // averages each 2x2 probe in c0
{
    const uint2 coord = did.xy;
    const uint2 c0_probe_size = 2; 
    const uint2 probe_id = coord / c0_probe_size; // assuming 1 probe every 2 pixels in c0
    const uint2 read = probe_id * c0_probe_size;
    float4 total = 0;
    [unroll]
    for (uint y = 0; y < c0_probe_size.y; y++)
    {
        [unroll]
        for (uint x = 0; x < c0_probe_size.x; x++)
        {
            const uint2 pos = read + uint2(x, y);
            total += g_finalCascade_min.Load(int3(pos, 0));
        }
    }
    o_finalCascadeUpscaled_min[coord] = total / (c0_probe_size.x*c0_probe_size.y);
}
